[package]
name = "time_travel_ling_hashmap"
version = "0.1.0"
edition = "2024"

[lib]
name = "time_travel_ling_hashmap"

[dependencies]
criterion = "0.6.0"

[[bench]]
name = "my_benchmark"
harness = false
