[package]
name = "proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.11"
gutils = { path = "../gutils", version = "*" }
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.101"
