name: Unitary Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-tex:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unitary Tests
        uses: cachix/install-nix-action@v31
        # Docs on https://github.com/marketplace/actions/install-nix
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: |
          cp .env.example .env
          nix-shell --run "cargo test --workspace"
